# Generated by Django 4.1.2 on 2022-10-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlajkt_cat_stat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acquisition',
        ),
        migrations.AlterField(
            model_name='catalogues',
            name='copycat',
            field=models.CharField(choices=[('No', 'No'), ('Partial copycat', 'Partial copycat'), ('Full copycat', 'Full copycat')], default='No', max_length=20),
        ),
    ]
