# Generated by Django 4.0.6 on 2022-10-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlajkt_cat_stat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('cons_no', models.IntegerField(default=461)),
                ('titles_proc', models.IntegerField()),
                ('vendor', models.CharField(choices=[('Yukendro', 'Yukendro'), ('Hariyanto', 'Hariyanto'), ('Meison/Syaiful', 'Meison/Syaiful'), ('Fuad', 'Fuad'), ('Komari', 'Komari'), ('Field trip', 'Field trip'), ('G/E', 'G/E')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book_source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Regular supplier', 'Regular supplier'), ('Book store', 'Book store'), ('Field trip', 'Field trip'), ('Gift/Exchange', 'Gift/Exchange')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consign_no', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='In process', max_length=50)),
                ('box_count', models.IntegerField(default=0)),
                ('total_weight', models.IntegerField(default=0)),
                ('shipment_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='catalogues',
            name='genre',
            field=models.CharField(choices=[('General non fiction', 'General non fiction'), ('Fiction-novel', 'Fiction-novel'), ('Fiction-short stories', 'Fiction-short stories'), ('Fiction-biographic', 'Fiction-biographic'), ('Poetry', 'Poetry'), ('Folktales', 'Folktales'), ('Biography-single', 'Biography-single'), ('Biography-collective', 'Biography-collective'), ('Biography-auto', 'Biography-auto'), ('Dictionaries', 'Dictionaries'), ('Proceeding', 'Proceeding')], default='General non fiction', max_length=100),
        ),
        migrations.AlterField(
            model_name='catalogues',
            name='subject',
            field=models.CharField(choices=[('000-Generalities', '100-Generalities'), ('000-Library science', '100-Library science'), ('000-Journalism and media', '100-Journalism and media'), ('100-Philosophy and ethics', '100-Philosophy and ethics'), ('200-Religions-general', '200-Religions-general'), ('200-Religion-Islam', '200-Religion-Islam'), ('200-Religion-Christianity', '200-Religion-Christianity'), ('200-Religion-Hinduism', '200-Religion-Hinduism'), ('200-Religion-Buddhism and others', '200-Religion-Buddhism and others'), ('300-Social-anthropology and sociology', '300-Social-anthropology and sociology'), ('300-Social-problems and services', '300-Social-problems and services'), ('300-Social-politics', '300-Social-politics'), ('300-Social-economics-general', '300-Social-economics-general'), ('300-Social-economics-resources', '300-Social-economics-resources'), ('300-Social-economics-policy and development', '300-Social-economics-policy and development'), ('300-Social-economics-financial and monetary', '300-Social-economics-financial and monetary'), ('300-Social-economics-industries and production', '300-Social-economics-industries and production'), ('300-Social-macroeconomics', '300-Social-macroeconomics'), ('300-Social-culture', '300-Social-culture'), ('300-Social-military', '300-Social-military'), ('300-Social-education', '300-Social-education'), ('300-Social-law', '300-Social-law'), ('300-Social-public administration', '300-Social-public administration'), ('300-Social-human rights', '300-Social-human rights'), ('400-Language-linguistics', '400-Language-linguistics'), ('400-Language-sociolinguistics', '400-Language-sociolinguistics'), ('500-Science-general', '500-Science-general'), ('600-Technology-general', '600-Technology-general'), ('600-Agriculture and agribusiness', '600-Agriculture and agribusiness'), ('700-Arts-general', '700-Arts-general'), ('700-Arts-visual', '700-Arts-visual'), ('700-Arts-performance', '700-Arts-performance'), ('700-Arts-music', '700-Arts-music'), ('800-Literature-general', '800-Literature-general'), ('800-Literature-fiction and poetry', '800-Literature-fiction and poetry'), ('900-History-world', '900-History-world'), ('900-History-Indonesia', '900-History-Indonesia'), ('900-Geography and travel', '900-Geography and travel'), ('900-Biography', '900-Biography')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Acquisition2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('cons_no', models.IntegerField(default=461)),
                ('titles_proc', models.IntegerField()),
                ('value', models.IntegerField(default=0)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nlajkt_cat_stat.book_source')),
            ],
        ),
    ]
