# Generated by Django 4.1.1 on 2022-10-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nlajkt_cat_stat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_date", models.DateField()),
                ("visit_date", models.DateField(blank=True, null=True)),
                ("titles_acq", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Completed", "Completed"),
                            ("Postponed", "Postponed"),
                            ("Canceled", "Canceled"),
                        ],
                        default="Scheduled",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip_place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_name", models.CharField(max_length=100)),
                (
                    "place_category",
                    models.CharField(
                        choices=[
                            ("Government office", "Government Office"),
                            ("NGO office", "NGO Office"),
                            ("Book store", "Book store"),
                            ("Book fair", "Book fair"),
                            ("Personal", "Personal"),
                        ],
                        max_length=100,
                    ),
                ),
                ("address", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="Acquisition",
        ),
        migrations.AlterField(
            model_name="catalogues",
            name="copycat",
            field=models.CharField(
                choices=[
                    ("No", "No"),
                    ("Partial copycat", "Partial copycat"),
                    ("Full copycat", "Full copycat"),
                ],
                default="No",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fieldtrip",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="nlajkt_cat_stat.trip_place",
            ),
        ),
    ]
