# Generated by Django 4.1.1 on 2022-10-21 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nlajkt_cat_stat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tripplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Government office", "Government office"),
                            ("NGO office", "NGO office"),
                            ("Book fair", "Book fair"),
                            ("Book store", "Book store"),
                            ("Personal", "Personal"),
                            ("Others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="catalogues",
            name="copycat",
            field=models.CharField(
                choices=[
                    ("No", "No"),
                    ("Partial copycat", "Partial copycat"),
                    ("Full copycat", "Full copycat"),
                ],
                default="No",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Fieldtrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planned_date", models.DateField()),
                ("visit_date", models.DateField(blank=True, null=True)),
                ("titles_acquired", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Visited", "Visited"),
                            ("Postponed", "Postponed"),
                            ("Canceled", "Canceled"),
                        ],
                        default="Scheduled",
                        max_length=100,
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nlajkt_cat_stat.tripplace",
                    ),
                ),
            ],
        ),
    ]
