# Generated by Django 4.1.1 on 2022-10-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nlajkt_cat_stat", "0003_cat_cons_alter_acquisition_cons_no_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cat_cons",
            old_name="new_itle",
            new_name="new_title",
        ),
    ]
