# Generated by Django 4.1.1 on 2023-08-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nlajkt_cat_stat", "0004_rename_new_itle_cat_cons_new_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat_cons",
            name="add_vol",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cat_cons",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cat_cons",
            name="new_title",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="catalogues",
            name="consignment_no",
            field=models.IntegerField(default=464),
        ),
        migrations.AlterField(
            model_name="catalogues",
            name="copycat",
            field=models.CharField(
                choices=[
                    ("Original", "Original"),
                    ("Partial copycat", "Partial copycat"),
                    ("Full copycat", "Full copycat"),
                ],
                default="Original",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="catalogues",
            name="format",
            field=models.CharField(
                choices=[
                    ("Book-printed", "Book-printed"),
                    ("Book-electronic", "Book-electronic"),
                    ("Non book video", "Non book video"),
                    ("Non book audio", "Non book audio"),
                    ("Map-single", "Map-single"),
                    ("Map-atlas", "Map-atlas"),
                    ("Ephemera", "Ephemera"),
                ],
                default="Book-printed",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="catalogues",
            name="genre",
            field=models.CharField(
                choices=[
                    ("General non fiction", "General non fiction"),
                    ("Fiction-novel", "Fiction-novel"),
                    ("Fiction-short stories", "Fiction-short stories"),
                    ("Fiction-biographic", "Fiction-biographic"),
                    ("Fiction-drama", "Fiction-drama"),
                    ("Poetry", "Poetry"),
                    ("Folktales", "Folktales"),
                    ("Biography-single", "Biography-single"),
                    ("Biography-collective", "Biography-collective"),
                    ("Biography-auto", "Biography-auto"),
                    ("Dictionaries", "Dictionaries"),
                    ("Proceeding", "Proceeding"),
                    ("Comic, cartoon", "Comic, cartoon"),
                ],
                default="General non fiction",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="catalogues",
            name="subject",
            field=models.CharField(
                choices=[
                    ("000-Generalities", "000-Generalities"),
                    ("000-Library science", "000-Library science"),
                    ("000-Journalism and media", "000-Journalism and media"),
                    ("100-Philosophy and ethics", "100-Philosophy and ethics"),
                    ("200-Religions-general", "200-Religions-general"),
                    ("200-Religion-Islam", "200-Religion-Islam"),
                    ("200-Religion-Christianity", "200-Religion-Christianity"),
                    ("200-Religion-Hinduism", "200-Religion-Hinduism"),
                    (
                        "200-Religion-Buddhism and others",
                        "200-Religion-Buddhism and others",
                    ),
                    (
                        "300-Social-anthropology and sociology",
                        "300-Social-anthropology and sociology",
                    ),
                    (
                        "300-Social-problems and services",
                        "300-Social-problems and services",
                    ),
                    ("300-Social-politics", "300-Social-politics"),
                    (
                        "300-Social-international relations",
                        "300-Social-international relations",
                    ),
                    ("300-Social-economics-general", "300-Social-economics-general"),
                    (
                        "300-Social-economics-management",
                        "300-Social-economics-management",
                    ),
                    (
                        "300-Social-economics-resources",
                        "300-Social-economics-resources",
                    ),
                    (
                        "300-Social-economics-policy and development",
                        "300-Social-economics-policy and development",
                    ),
                    (
                        "300-Social-economics-financial and monetary",
                        "300-Social-economics-financial and monetary",
                    ),
                    (
                        "300-Social-economics-industries and production",
                        "300-Social-economics-industries and production",
                    ),
                    ("300-Social-culture", "300-Social-culture"),
                    ("300-Social-military", "300-Social-military"),
                    ("300-Social-education", "300-Social-education"),
                    ("300-Social-law", "300-Social-law"),
                    ("300-Social-transportation", "300-Social-transportation"),
                    (
                        "300-Social-public administration",
                        "300-Social-public administration",
                    ),
                    ("300-Social-human rights", "300-Social-human rights"),
                    ("400-Language-linguistics", "400-Language-linguistics"),
                    ("400-Language-sociolinguistics", "400-Language-sociolinguistics"),
                    ("500-Science-general", "500-Science-general"),
                    ("600-Technology-general", "600-Technology-general"),
                    (
                        "600-Agriculture and agribusiness",
                        "600-Agriculture and agribusiness",
                    ),
                    ("700-Arts-general", "700-Arts-general"),
                    ("700-Arts-visual", "700-Arts-visual"),
                    ("700-Arts-performance", "700-Arts-performance"),
                    ("700-Arts-music", "700-Arts-music"),
                    ("700-Architecture", "700-Architecture"),
                    ("800-Literature-general", "800-Literature-general"),
                    (
                        "800-Literature-fiction and poetry",
                        "800-Literature-fiction and poetry",
                    ),
                    ("900-History-general", "900-History-general"),
                    ("900-History-Indonesia", "900-History-Indonesia"),
                    ("900-Geography and travel", "900-Geography and travel"),
                    ("900-Biography", "900-Biography"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
