# Generated by Django 4.1 on 2022-09-22 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('consignment_no', models.IntegerField(default=461)),
                ('title', models.TextField()),
                ('work_type', models.CharField(choices=[('Original', 'Original'), ('Translation', 'Translation'), ('Adaptation', 'Adaptation')], default='Original', max_length=20)),
                ('publish_year', models.IntegerField()),
                ('volume', models.CharField(choices=[('Single', 'Single'), ('Multi-complete', 'Multi-complete'), ('Multi-incomplete', 'Multi-incomplete')], default='Single', max_length=20)),
                ('copycat', models.CharField(choices=[('No', 'No'), ('Yes-partial', 'Yes-partial'), ('Yes-full', 'Yes-full')], default='No', max_length=20)),
                ('ISBN', models.CharField(choices=[('No', 'No'), ('Yes-valid', 'Yes-valid'), ('Yes-invalid', 'Yes-invalid')], default='No', max_length=20)),
                ('authorship_type', models.CharField(choices=[('Single author', 'Single author'), ('Collaboration', 'Collaboration'), ('Compilation', 'Compilation'), ('Others', 'Others')], default='Single', max_length=50)),
                ('language', models.CharField(choices=[('Indonesian', 'Indonesian'), ('English', 'English'), ('Indonesian local', 'Indonesian local'), ('Multi language', 'Multi language'), ('Unknown', 'Unknown')], default='Indonesian', max_length=50)),
                ('bibliography', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=20)),
                ('indexx', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=20)),
                ('publisher_type', models.CharField(choices=[('Commercial', 'Commercial'), ('Government-department', 'Government-department'), ('Government-nondepartment', 'Government-nondepartment'), ('Government-local', 'Government-local'), ('Universities', 'Universities'), ('NGO', 'NGO'), ('Others', 'Others')], default='Commercial', max_length=100)),
                ('genre', models.CharField(choices=[('General non fiction', 'General non fiction'), ('Fiction-novel', 'Fiction-novel'), ('Fiction-short stories', 'Fiction-short stories'), ('Poetry', 'Poetry'), ('Folktales', 'Folktales'), ('Biography-single', 'Biography-single'), ('Biography-collective', 'Biography-collective'), ('Biography-auto', 'Biography-auto'), ('Dictionary', 'Dictionary')], default='General non fiction', max_length=100)),
                ('format', models.CharField(choices=[('Book-printed', 'Book-printed'), ('Book-electronic', 'Book-electronic'), ('Non book video', 'Non book video'), ('Non book audio', 'Non book audio'), ('Map-single', 'Map-single'), ('Map-atlas', 'Map-atlas'), ('Ephemera', 'Ephemera')], default='Book', max_length=100)),
                ('size', models.CharField(choices=[('YY', 'YY'), ('YYq', 'YYq'), ('YYp', 'YYp')], default='YY', max_length=10)),
                ('subject', models.CharField(choices=[('000-Generalities', '100-Generalities'), ('000-Library science', '100-Library science'), ('000-Journalism and media', '100-Journalism and media'), ('100-Philosophy and ethics', '100-Philosophy and ethics'), ('200-Religions-general', '200-Religions-general'), ('200-Religion-Islam', '200-Religion-Islam'), ('200-Religion-Christianity', '200-Religion-Christianity'), ('300-Social-anthropology and sociology', '300-Social-anthropology and sociology'), ('300-Social-problems and services', '300-Social-problems and services'), ('300-Social-politics', '300-Social-politics'), ('300-Social-economics', '300-Social-economics'), ('300-Social-macroeconomics', '300-Social-macroeconomics'), ('300-Social-culture', '300-Social-culture'), ('300-Social-military', '300-Social-military'), ('300-Social-education', '300-Social-education'), ('300-Social-law', '300-Social-law'), ('400-Language-linguistics', '400-Language-linguistics'), ('400-Language-sociolinguistics', '400-Language-sociolinguistics'), ('500-Science-general', '500-Science-general'), ('600-Technology-general', '600-Technology-general'), ('600-Agriculture and agribusiness', '600-Agriculture and agribusiness'), ('700-Arts-general', '700-Arts-general'), ('700-Arts-visual', '700-Arts-visual'), ('700-Arts-performance', '700-Arts-performance'), ('700-Arts-music', '700-Arts-music'), ('800-Literature-general', '800-Literature-general'), ('800-Literature-fiction and poetry', '800-Literature-fiction and poetry'), ('900-History-world', '900-History-world'), ('900-History-Indonesia', '900-History-Indonesia'), ('900-Geography and travel', '900-Geography and travel'), ('900-Biography', '900-Biography')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('population', models.PositiveIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catstat.country')),
            ],
        ),
    ]
